services:
  nodeserver:
    build:
      context: .
    environment:
      VIRTUAL_HOST: 'wscnettie.com'
      VIRTUAL_PORT: 3000
      LETSENCRYPT_HOST: 'wscnettie.com'
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
    restart: unless-stopped

  nginx-proxy:
    container_name: nginx-proxy
    build:
      context: ./nginx
    volumes:
      - certs:/etc/nginx/certs:ro
      - /etc/nginx/vhost.d
      - /etc/acme.sh
      - /usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - '80:80'
      - '443:443'
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: ''
    restart: unless-stopped

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    environment:
      NGINX_DOCKER_GEN_CONTAINER: nginx-proxy
    volumes:
      - certs:/etc/nginx/certs/
      - /var/run/docker.sock:/var/run/docker.sock:ro
    volumes_from:
      - nginx-proxy
    restart: unless-stopped
    depends_on:
      - nginx-proxy

volumes:
  certs:
